[versions]
# libraries
junit4 = "4.13.2"
junit5 = "6.0.2"
opentest4j = "1.3.0"
log4j = "2.25.3"
jackson = "2.19.1"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
kover = "0.9.6"
qodana = "2025.3.1"

[libraries]
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
# Log4J
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
# Jackson
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }

[bundles]
log4j = ["log4j-api", "log4j-core"]
jackson = ["jackson-annotations", "jackson-core", "jackson-databind", "jackson-xml"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
